name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  push_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: ./.github/actions/push_action
        with:
          push: "push"
          actor: "tex4gmail"
          token: ${{ secrets.texforgmail }}
          version: ${{ steps.get_version.outputs.VERSION }}
